#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : OpenIPMI
Version  : 2.0.33
Release  : 40
URL      : https://sourceforge.net/projects/openipmi/files/OpenIPMI%202.0%20Library/OpenIPMI-2.0.33.tar.gz
Source0  : https://sourceforge.net/projects/openipmi/files/OpenIPMI%202.0%20Library/OpenIPMI-2.0.33.tar.gz
Summary  : %{name} - Library interface to IPMI
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.1
BuildRequires : pkgconfig(libedit)
BuildRequires : python3-dev
Patch1: 0001-Update-for-python-3.10.patch

%description
This is the OpenIPMI library, a library that makes simplifies building
complex IPMI management software.

%prep
%setup -q -n OpenIPMI-2.0.33
cd %{_builddir}/OpenIPMI-2.0.33
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666628477
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%reconfigure --disable-static --with-perl=no
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1666628477
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/OpenIPMI
cp %{_builddir}/OpenIPMI-%{version}/COPYING %{buildroot}/usr/share/package-licenses/OpenIPMI/dfac199a7539a404407098a2541b9482279f690d || :
cp %{_builddir}/OpenIPMI-%{version}/COPYING.BSD %{buildroot}/usr/share/package-licenses/OpenIPMI/6041dfa4b268e7399d2c7e18c644cb291982028a || :
cp %{_builddir}/OpenIPMI-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/OpenIPMI/cf756914ec51f52f9c121be247bfda232dc6afd2 || :
%make_install

%files
%defattr(-,root,root,-)
