#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v18
# autospec commit: f35655a
#
Name     : OpenIPMI
Version  : 2.0.36
Release  : 48
URL      : https://sourceforge.net/projects/openipmi/files/OpenIPMI%202.0%20Library/OpenIPMI-2.0.36.tar.gz
Source0  : https://sourceforge.net/projects/openipmi/files/OpenIPMI%202.0%20Library/OpenIPMI-2.0.36.tar.gz
Summary  : %{name} - Library interface to IPMI
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.1
Requires: OpenIPMI-bin = %{version}-%{release}
Requires: OpenIPMI-lib = %{version}-%{release}
Requires: OpenIPMI-license = %{version}-%{release}
Requires: OpenIPMI-man = %{version}-%{release}
Requires: OpenIPMI-python = %{version}-%{release}
Requires: OpenIPMI-python3 = %{version}-%{release}
BuildRequires : file
BuildRequires : gdbm-dev
BuildRequires : pkgconfig(libedit)
BuildRequires : popt-dev
BuildRequires : python3-dev
BuildRequires : readline-dev
BuildRequires : swig
BuildRequires : tcl
BuildRequires : texlive
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is the OpenIPMI library, a library that makes simplifies building
complex IPMI management software.

%package bin
Summary: bin components for the OpenIPMI package.
Group: Binaries
Requires: OpenIPMI-license = %{version}-%{release}

%description bin
bin components for the OpenIPMI package.


%package dev
Summary: dev components for the OpenIPMI package.
Group: Development
Requires: OpenIPMI-lib = %{version}-%{release}
Requires: OpenIPMI-bin = %{version}-%{release}
Provides: OpenIPMI-devel = %{version}-%{release}
Requires: OpenIPMI = %{version}-%{release}

%description dev
dev components for the OpenIPMI package.


%package lib
Summary: lib components for the OpenIPMI package.
Group: Libraries
Requires: OpenIPMI-license = %{version}-%{release}

%description lib
lib components for the OpenIPMI package.


%package license
Summary: license components for the OpenIPMI package.
Group: Default

%description license
license components for the OpenIPMI package.


%package man
Summary: man components for the OpenIPMI package.
Group: Default

%description man
man components for the OpenIPMI package.


%package python
Summary: python components for the OpenIPMI package.
Group: Default
Requires: OpenIPMI-python3 = %{version}-%{release}
Provides: openipmi-python

%description python
python components for the OpenIPMI package.


%package python3
Summary: python3 components for the OpenIPMI package.
Group: Default
Requires: python3-core

%description python3
python3 components for the OpenIPMI package.


%prep
%setup -q -n OpenIPMI-2.0.36
cd %{_builddir}/OpenIPMI-2.0.36
pushd ..
cp -a OpenIPMI-2.0.36 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722612236
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static --with-perl=no
make  %{?_smp_mflags}
unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%reconfigure --disable-static --with-perl=no
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1722612236
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/OpenIPMI
cp %{_builddir}/OpenIPMI-%{version}/COPYING %{buildroot}/usr/share/package-licenses/OpenIPMI/dfac199a7539a404407098a2541b9482279f690d || :
cp %{_builddir}/OpenIPMI-%{version}/COPYING.BSD %{buildroot}/usr/share/package-licenses/OpenIPMI/6041dfa4b268e7399d2c7e18c644cb291982028a || :
cp %{_builddir}/OpenIPMI-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/OpenIPMI/cf756914ec51f52f9c121be247bfda232dc6afd2 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/ipmi_sim
/V3/usr/bin/ipmi_ui
/V3/usr/bin/ipmilan
/V3/usr/bin/openipmi_eventd
/V3/usr/bin/openipmicmd
/V3/usr/bin/openipmish
/V3/usr/bin/rmcp_ping
/V3/usr/bin/sdrcomp
/V3/usr/bin/solterm
/usr/bin/ipmi_sim
/usr/bin/ipmi_ui
/usr/bin/ipmicmd
/usr/bin/ipmilan
/usr/bin/ipmish
/usr/bin/openipmi_eventd
/usr/bin/openipmicmd
/usr/bin/openipmish
/usr/bin/rmcp_ping
/usr/bin/sdrcomp
/usr/bin/solterm

%files dev
%defattr(-,root,root,-)
/usr/include/OpenIPMI/deprecator.h
/usr/include/OpenIPMI/dllvisibility.h
/usr/include/OpenIPMI/extcmd.h
/usr/include/OpenIPMI/internal/ilist.h
/usr/include/OpenIPMI/internal/ipmi_control.h
/usr/include/OpenIPMI/internal/ipmi_domain.h
/usr/include/OpenIPMI/internal/ipmi_entity.h
/usr/include/OpenIPMI/internal/ipmi_event.h
/usr/include/OpenIPMI/internal/ipmi_fru.h
/usr/include/OpenIPMI/internal/ipmi_int.h
/usr/include/OpenIPMI/internal/ipmi_locks.h
/usr/include/OpenIPMI/internal/ipmi_malloc.h
/usr/include/OpenIPMI/internal/ipmi_mc.h
/usr/include/OpenIPMI/internal/ipmi_oem.h
/usr/include/OpenIPMI/internal/ipmi_sel.h
/usr/include/OpenIPMI/internal/ipmi_sensor.h
/usr/include/OpenIPMI/internal/ipmi_utils.h
/usr/include/OpenIPMI/internal/locked_list.h
/usr/include/OpenIPMI/internal/md2.h
/usr/include/OpenIPMI/internal/md5.h
/usr/include/OpenIPMI/internal/opq.h
/usr/include/OpenIPMI/internal/winsock_compat.h
/usr/include/OpenIPMI/ipmbserv.h
/usr/include/OpenIPMI/ipmi_addr.h
/usr/include/OpenIPMI/ipmi_auth.h
/usr/include/OpenIPMI/ipmi_bits.h
/usr/include/OpenIPMI/ipmi_cmdlang.h
/usr/include/OpenIPMI/ipmi_conn.h
/usr/include/OpenIPMI/ipmi_debug.h
/usr/include/OpenIPMI/ipmi_err.h
/usr/include/OpenIPMI/ipmi_fru.h
/usr/include/OpenIPMI/ipmi_glib.h
/usr/include/OpenIPMI/ipmi_lan.h
/usr/include/OpenIPMI/ipmi_lanparm.h
/usr/include/OpenIPMI/ipmi_log.h
/usr/include/OpenIPMI/ipmi_mc.h
/usr/include/OpenIPMI/ipmi_msgbits.h
/usr/include/OpenIPMI/ipmi_pef.h
/usr/include/OpenIPMI/ipmi_pet.h
/usr/include/OpenIPMI/ipmi_picmg.h
/usr/include/OpenIPMI/ipmi_posix.h
/usr/include/OpenIPMI/ipmi_sdr.h
/usr/include/OpenIPMI/ipmi_smi.h
/usr/include/OpenIPMI/ipmi_sol.h
/usr/include/OpenIPMI/ipmi_solparm.h
/usr/include/OpenIPMI/ipmi_string.h
/usr/include/OpenIPMI/ipmi_tcl.h
/usr/include/OpenIPMI/ipmi_types.h
/usr/include/OpenIPMI/ipmi_ui.h
/usr/include/OpenIPMI/ipmi_user.h
/usr/include/OpenIPMI/ipmiif.h
/usr/include/OpenIPMI/lanserv.h
/usr/include/OpenIPMI/lanserv_dllvisibility.h
/usr/include/OpenIPMI/mcserv.h
/usr/include/OpenIPMI/msg.h
/usr/include/OpenIPMI/mxp.h
/usr/include/OpenIPMI/os_handler.h
/usr/include/OpenIPMI/persist.h
/usr/include/OpenIPMI/selector.h
/usr/include/OpenIPMI/serserv.h
/usr/include/OpenIPMI/serv.h
/usr/lib64/libIPMIlanserv.so
/usr/lib64/libOpenIPMI.so
/usr/lib64/libOpenIPMIcmdlang.so
/usr/lib64/libOpenIPMIposix.so
/usr/lib64/libOpenIPMIpthread.so
/usr/lib64/libOpenIPMIui.so
/usr/lib64/libOpenIPMIutils.so
/usr/lib64/pkgconfig/OpenIPMI.pc
/usr/lib64/pkgconfig/OpenIPMIcmdlang.pc
/usr/lib64/pkgconfig/OpenIPMIposix.pc
/usr/lib64/pkgconfig/OpenIPMIpthread.pc
/usr/lib64/pkgconfig/OpenIPMIui.pc
/usr/lib64/pkgconfig/OpenIPMIutils.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libIPMIlanserv.so.0.0.1
/V3/usr/lib64/libOpenIPMI.so.0.0.5
/V3/usr/lib64/libOpenIPMIcmdlang.so.0.0.5
/V3/usr/lib64/libOpenIPMIposix.so.0.0.1
/V3/usr/lib64/libOpenIPMIpthread.so.0.0.1
/V3/usr/lib64/libOpenIPMIui.so.1.0.1
/V3/usr/lib64/libOpenIPMIutils.so.0.0.1
/usr/lib64/libIPMIlanserv.so.0
/usr/lib64/libIPMIlanserv.so.0.0.1
/usr/lib64/libOpenIPMI.so.0
/usr/lib64/libOpenIPMI.so.0.0.5
/usr/lib64/libOpenIPMIcmdlang.so.0
/usr/lib64/libOpenIPMIcmdlang.so.0.0.5
/usr/lib64/libOpenIPMIposix.so.0
/usr/lib64/libOpenIPMIposix.so.0.0.1
/usr/lib64/libOpenIPMIpthread.so.0
/usr/lib64/libOpenIPMIpthread.so.0.0.1
/usr/lib64/libOpenIPMIui.so.1
/usr/lib64/libOpenIPMIui.so.1.0.1
/usr/lib64/libOpenIPMIutils.so.0
/usr/lib64/libOpenIPMIutils.so.0.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/OpenIPMI/6041dfa4b268e7399d2c7e18c644cb291982028a
/usr/share/package-licenses/OpenIPMI/cf756914ec51f52f9c121be247bfda232dc6afd2
/usr/share/package-licenses/OpenIPMI/dfac199a7539a404407098a2541b9482279f690d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ipmi_sim.1
/usr/share/man/man1/ipmi_ui.1
/usr/share/man/man1/openipmi_eventd.1
/usr/share/man/man1/openipmicmd.1
/usr/share/man/man1/openipmigui.1
/usr/share/man/man1/openipmish.1
/usr/share/man/man1/rmcp_ping.1
/usr/share/man/man1/solterm.1
/usr/share/man/man5/ipmi_lan.5
/usr/share/man/man5/ipmi_sim_cmd.5
/usr/share/man/man7/ipmi_cmdlang.7
/usr/share/man/man7/openipmi_conparms.7
/usr/share/man/man8/ipmilan.8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
